// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urndwiimolxscwebrefs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVybmR3aWltb2x4c2N3ZWJyZWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTgzODYsImV4cCI6MjA2MTMzNDM4Nn0._aXNOuAI0Eb2V1iYeGt167tRlOkpcGgsLaaFfVK68SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);